<a href="https://colab.research.google.com/github/Sudeepthi-235/MDS-LAB/blob/main/MDS_WEEK_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [182]:
# Installing numpy library
!pip install numpy

SyntaxError: invalid syntax (731946320.py, line 2)

In [183]:
# Importing and finding the version of numpy
import numpy as np
print(np.__version__)

2.0.2


In [184]:
# Creation of list
list=[101,2,3,4,5]
type(list)

list

In [185]:
# Converting list into array
arr1=np.array(list)

In [186]:
# Printing the array
print(arr1)

[101   2   3   4   5]


In [187]:
# Finding type of array
type(arr1)

numpy.ndarray

In [188]:
# Dimension of array
arr1.ndim

1

In [189]:
# Datatype of array
arr1.dtype

dtype('int64')

In [190]:
# Only to print the name of type of array
arr1.dtype.name

'int64'

In [191]:
# Finding the size of array
arr1.size

5

In [192]:
# Finding shape of array
arr1.shape

(5,)

In [193]:
# Number of bytes used
arr1.nbytes

40

In [194]:
# Tuple creation
tuple=(101,2,3,5)

In [195]:
# Datatype of tuple
type(tuple)

tuple

In [196]:
# Creation of single element tuple array
tuple1=(101)

In [197]:
# Type of single element tuple
type(tuple1)

int

In [198]:
# Single element tuple
tuple2=(101,)

In [199]:
# Type of single element tuple
type(tuple2)

tuple

In [200]:
# Converting tuple to array
arr2=np.array(tuple)

In [201]:
# Printing array arr2
print(arr2)

[101   2   3   5]


In [202]:
# Array dimension
arr2.ndim

1

In [203]:
# Shape of array
arr2.shape

(4,)

In [204]:
# Bytes in array
arr2.nbytes

32

In [205]:
# Creation of 2-dimension list
list10=[[101,2],[3,4]]

In [206]:
# Converting list to array
matrix=np.array(list10)

In [207]:
# Print array
print(matrix)

[[101   2]
 [  3   4]]


In [208]:
# Dimensions of array
matrix.ndim

2

In [209]:
# Bytes of array
matrix.nbytes

32

In [210]:
# Converting back into single dimension using flatten()
matrix.flatten()

array([101,   2,   3,   4])

In [211]:
# Converting into single dimension using ravel()
matrix.ravel()

array([101,   2,   3,   4])

In [212]:
# Array creation using numpy
arr4=np.array([101,2,3,4])

In [213]:
# Printing array
print(arr4)

[101   2   3   4]


In [214]:
# 2-d array creation using numpy
arr5=np.array([[101,2],[3,4]])

In [215]:
# Printing the array
print(arr5)

[[101   2]
 [  3   4]]


In [216]:
# 2d array using numpy
arr6=np.matrix([[101,2],[3,4],[5,6]])

In [217]:
# Printing array
print(arr6)

[[101   2]
 [  3   4]
 [  5   6]]


In [218]:
# Array with arange() function
arr7=np.arange(101,200)

In [219]:
# Array print
print(arr7)

[101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136
 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154
 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172
 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190
 191 192 193 194 195 196 197 198 199]


In [220]:
# Only even numbers in range
arr8=np.arange(100,200,2)

In [221]:
# Printing array
print(arr8)

[100 102 104 106 108 110 112 114 116 118 120 122 124 126 128 130 132 134
 136 138 140 142 144 146 148 150 152 154 156 158 160 162 164 166 168 170
 172 174 176 178 180 182 184 186 188 190 192 194 196 198]


In [265]:
# Only even numbers
arr10=np.arange(101,step=2)

In [264]:
# Printing array
print(arr10)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


In [263]:
# Reshaping an array
matrix2=np.arange(0,10).reshape(2,5)

In [262]:
# Printing matrix2
print(matrix2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [261]:
# Flattening matrix2
matrix2.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [227]:
# Creating a 3x3 array of zeros
a=np.zeros((3,3),dtype='int')

In [228]:
# Printing array 'a'
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [229]:
# Getting the data type name of array 'a'
a.dtype.name

'int64'

In [230]:
# Creating a 3x3 array of ones
b=np.ones((3,3),dtype='int')

In [231]:
# Printing array 'b'
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [232]:
# Getting the data type name of array 'b'
b.dtype.name

'int64'

In [233]:
# Creating a 3x3 array filled with '2'
c=np.full((3,3),2)

In [234]:
# Printing array 'c'
print(c)

[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [235]:
# Creating a 10x10 array filled with '5'
d=np.full((10,10),5)

In [236]:
# Printing array 'd'
print(d)

[[5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5 5]]


In [237]:
# Creating an identity matrix
e=np.eye(3)

In [238]:
# Printing array 'e'
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [239]:
# Creating an array with linearly spaced values
f=np.linspace(0,1,5)

In [240]:
# Printing array 'f'
print(f)

[0.   0.25 0.5  0.75 1.  ]


In [241]:
# Importing random module
import random as random

In [242]:
# Creating a 3x3 array with random floats
g=np.random.random((3,3))

In [243]:
# Printing array 'g'
print(g)

[[0.6178232  0.51264907 0.23749001]
 [0.91026574 0.57547823 0.27355283]
 [0.24358254 0.96022123 0.76604001]]


In [244]:
# Creating an array with arange()
arr11=np.arange(1,10)

In [245]:
# Printing array arr11
print(arr11)

[1 2 3 4 5 6 7 8 9]


In [255]:
# Modifying an element in arr11
arr11[0]=101

In [256]:
# Printing modified arr11
print(arr11)

[101   2 333 444 555   6   7   8   9]


In [248]:
# Attempting to assign a string to an integer array element
# arr11[2]="dsc"

ValueError: invalid literal for int() with base 10: 'dsc'

In [249]:
# Modifying a slice of arr11
arr11[2:5]=[333,444,555]

In [257]:
# Printing arr11 after slice modification
print(arr11)

[101   2 333 444 555   6   7   8   9]


In [258]:
# Finding the maximum value in arr11
arr11.max()

np.int64(555)

In [259]:
# Finding the minimum value in arr11
arr11.min()

np.int64(2)

In [260]:
# Calculating the mean of arr11
arr11.mean()

np.float64(162.77777777777777)