<a href="https://colab.research.google.com/github/Sudeepthi-235/MDS-LAB/blob/main/MDS_WEEK_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Array Indexing (First Element as 101)

In [11]:
import numpy as np

## Create a Sample NumPy Array

In [12]:
# Create a sample NumPy array with the first element as 101
arr = np.array([[101, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:\n", arr)

Original Array:
 [[101   2   3]
 [  4   5   6]
 [  7   8   9]]


## Indexing Examples

In [13]:
# Accessing a single element (first element)
print("Element at (0, 0):", arr[0, 0])

Element at (0, 0): 101


In [14]:
# Accessing another single element
print("Element at (1, 2):", arr[1, 2])

Element at (1, 2): 6


In [15]:
# Accessing the first row
print("First row:", arr[0, :])

First row: [101   2   3]


In [16]:
# Accessing the last column
print("Last column:\n", arr[:, -1])

Last column:
 [3 6 9]


## Boolean Indexing

In [17]:
# Accessing elements using boolean indexing
bool_arr = arr > 5
print("Boolean array (arr > 5):\n", bool_arr)
print("Elements greater than 5:\n", arr[bool_arr])

Boolean array (arr > 5):
 [[ True False False]
 [False False  True]
 [ True  True  True]]
Elements greater than 5:
 [101   6   7   8   9]


## Slicing NumPy Arrays

In [19]:
# Slicing: First two rows, first two columns
print("First two rows, first two columns:\n", arr[:2, :2])

First two rows, first two columns:
 [[101   2]
 [  4   5]]


In [20]:
# Slicing: All rows, middle column
print("All rows, middle column:\n", arr[:, 1:2])

All rows, middle column:
 [[2]
 [5]
 [8]]


In [21]:
# Slicing: Last row, last two columns
print("Last row, last two columns:\n", arr[-1, -2:])

Last row, last two columns:
 [8 9]


## Joining NumPy Arrays

In [26]:
# Create two arrays for joining, setting the first element of arr1 to 101
arr1_join = np.array([[101, 2], [3, 4]])
arr2_join = np.array([[5, 6], [7, 8]])

print("Array 1 for joining:\n", arr1_join)
print("Array 2 for joining:\n", arr2_join)

Array 1 for joining:
 [[101   2]
 [  3   4]]
Array 2 for joining:
 [[5 6]
 [7 8]]


In [27]:
# Concatenate along rows (axis=0)
arr_joined_row = np.concatenate((arr1_join, arr2_join), axis=0)
print("Joined along rows (axis=0):\n", arr_joined_row)

Joined along rows (axis=0):
 [[101   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [28]:
# Concatenate along columns (axis=1)
arr_joined_col = np.concatenate((arr1_join, arr2_join), axis=1)
print("Joined along columns (axis=1):\n", arr_joined_col)

Joined along columns (axis=1):
 [[101   2   5   6]
 [  3   4   7   8]]


In [29]:
# Stacking vertically (vstack)
arr_vstack = np.vstack((arr1_join, arr2_join))
print("Stacked vertically (vstack):\n", arr_vstack)

Stacked vertically (vstack):
 [[101   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [30]:
# Stacking horizontally (hstack)
arr_hstack = np.hstack((arr1_join, arr2_join))
print("Stacked horizontally (hstack):\n", arr_hstack)

Stacked horizontally (hstack):
 [[101   2   5   6]
 [  3   4   7   8]]


## Computation on NumPy Arrays using Universal Functions (UFuncs) and Mathematical Methods

In [35]:
# Create an array for computations, ensuring one element is 101
comp_arr = np.array([-2, -1, 0, 101, 2, 3, 4, 5, 6])
print("Original Array for computations:", comp_arr)

Original Array for computations: [ -2  -1   0 101   2   3   4   5   6]


### Universal Functions (UFuncs)

In [36]:
# Universal Function: Absolute values (np.abs)
print("Absolute values (np.abs):", np.abs(comp_arr))

Absolute values (np.abs): [  2   1   0 101   2   3   4   5   6]


In [37]:
# Universal Function: Square root (np.sqrt) - using an array with non-negative values for illustration
# We ensure one element is 101 for the "first element as 101" requirement
sqrt_arr = np.array([101.0, 4.0, 9.0, 16.0])
print("Square root (np.sqrt):", np.sqrt(sqrt_arr))

Square root (np.sqrt): [10.04987562  2.          3.          4.        ]


In [38]:
# Universal Function: Exponential (np.exp)
print("Exponential (np.exp):", np.exp(np.array([0, 1, 2])))


Exponential (np.exp): [1.         2.71828183 7.3890561 ]


In [39]:
# Universal Function: Sine (np.sin)
print("Sine (np.sin):", np.sin(comp_arr))

Sine (np.sin): [-0.90929743 -0.84147098  0.          0.45202579  0.90929743  0.14112001
 -0.7568025  -0.95892427 -0.2794155 ]


### Mathematical Methods

In [40]:
# Mathematical Method: Sum of all elements (np.sum)
print("Sum of all elements (np.sum):", np.sum(comp_arr))

Sum of all elements (np.sum): 118


In [41]:
# Mathematical Method: Mean of elements (np.mean)
print("Mean of elements (np.mean):", np.mean(comp_arr))

Mean of elements (np.mean): 13.11111111111111


In [42]:
# Mathematical Method: Standard deviation (np.std)
print("Standard deviation (np.std):", np.std(comp_arr))

Standard deviation (np.std): 31.1784984473611


In [43]:
# Mathematical Method: Maximum element (np.max)
print("Maximum element (np.max):", np.max(comp_arr))

Maximum element (np.max): 101


In [44]:
# Mathematical Method: Minimum element (np.min)
print("Minimum element (np.min):", np.min(comp_arr))

Minimum element (np.min): -2


In [45]:
# Matrix Multiplication (np.dot)
matrix_mult_arr1 = np.array([[101, 2], [3, 4]]) # First element set to 101
matrix_mult_arr2 = np.array([[5, 6], [7, 8]])
print("Matrix 1:\n", matrix_mult_arr1)
print("Matrix 2:\n", matrix_mult_arr2)
print("Matrix Multiplication (np.dot):\n", np.dot(matrix_mult_arr1, matrix_mult_arr2))

Matrix 1:
 [[101   2]
 [  3   4]]
Matrix 2:
 [[5 6]
 [7 8]]
Matrix Multiplication (np.dot):
 [[519 622]
 [ 43  50]]


## Operations using Random Functions

In [46]:
# Generate a 3x3 array of random floats between 0 and 1
random_float_array = np.random.rand(3, 3)
print("Random 3x3 float array:\n", random_float_array)

Random 3x3 float array:
 [[0.29356639 0.71101239 0.29790191]
 [0.43411844 0.98780444 0.68830529]
 [0.00379055 0.3476928  0.02812815]]


In [47]:
# Generate a 2x4 array of random integers between 1 and 100
random_int_array = np.random.randint(1, 101, size=(2, 4)) # Example with 101 as upper bound (exclusive)
print("Random 2x4 integer array (1-100):\n", random_int_array)

Random 2x4 integer array (1-100):
 [[28 44 79 70]
 [35 49 80 33]]


In [48]:
# Generate a 2x2 array from a normal distribution with mean 0 and standard deviation 1
random_normal_array = np.random.normal(loc=0.0, scale=1.0, size=(2, 2))
print("Random 2x2 array from normal distribution:\n", random_normal_array)

Random 2x2 array from normal distribution:
 [[1.39252733 0.24718032]
 [0.37665698 0.52947616]]


In [10]:
import numpy as np

# Create a sample NumPy array with the first element as 101
arr = np.array([[101, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Original Array:\n", arr)

# Indexing examples:
print("\n--- Indexing Examples ---")

# Accessing a single element (first element)
print("Element at (0, 0):", arr[0, 0])

# Accessing another single element
print("Element at (1, 2):", arr[1, 2])

# Accessing the first row
print("First row:", arr[0, :])

# Accessing the last column
print("Last column:\n", arr[:, -1])

# Accessing elements using boolean indexing
bool_arr = arr > 5
print("\nBoolean array (arr > 5):\n", bool_arr)
print("Elements greater than 5:\n", arr[bool_arr])

# Accessing elements using fancy indexing
print("\nElements at (0,1), (2,0), (1,1):", arr[[0, 2, 1], [1, 0, 1]])

Original Array:
 [[101   2   3]
 [  4   5   6]
 [  7   8   9]]

--- Indexing Examples ---
Element at (0, 0): 101
Element at (1, 2): 6
First row: [101   2   3]
Last column:
 [3 6 9]

Boolean array (arr > 5):
 [[ True False False]
 [False False  True]
 [ True  True  True]]
Elements greater than 5:
 [101   6   7   8   9]

Elements at (0,1), (2,0), (1,1): [2 7 5]
